export const sponsors = [
  { name: "ASKI", src: "/images/sponsor/aski.png" },
  { name: "Akebono", src: "/images/sponsor/akebono.png" },
  { name: "Astra Otoparts", src: "/images/sponsor/astra-otoparts.png" },
  { name: "Atria Hotel", src: "/images/sponsor/atria-hotel.png" },
  { name: "CIMB Niaga", src: "/images/sponsor/cimb-niaga.png" },
  { name: "DEUS", src: "/images/sponsor/deus.png" },
  { name: "Danamon", src: "/images/sponsor/danamon.png" },
  { name: "Djarum 76", src: "/images/sponsor/djarum-76.png" },
  { name: "ESB", src: "/images/sponsor/esb.png" },
  { name: "Evertops", src: "/images/sponsor/evertops.png" },
  { name: "Happy Kiddy", src: "/images/sponsor/happy-kiddy.png" },
  { name: "Honda", src: "/images/sponsor/honda.png" },
  { name: "Hooray", src: "/images/sponsor/hooray.png" },
  { name: "IST", src: "/images/sponsor/ist.png" },
  { name: "Lippo Group", src: "/images/sponsor/lippo-group.png" },
  { name: "Megapro", src: "/images/sponsor/megapro.png" },
  { name: "Parador", src: "/images/sponsor/parador.png" },
  { name: "Rimaunangis", src: "/images/sponsor/rimaunangis.png" },
  { name: "TerraDrone", src: "/images/sponsor/terradrone.png" },
  { name: "UrbanX", src: "/images/sponsor/urbanx.png" },
  { name: "Winteq", src: "/images/sponsor/winteq.png" },
] as const;
